name: "multi event pipeline"  #Name of pipeline

# control when the actions will run. riggers the workflow on push somethin to master

on:  #Event : whenever push is made pn master
    push:
        branches:
            - master
            - test
            

jobs:
    onpush:     #jobname
        runs-on: ubuntu-latest
        steps: #steps to be executed
            - name: "Running on master push"
              run: echo "Running on master push"
